# tekartik flutter recommended lints (extension over google lints and pedantic)
analyzer:
  errors:
    depend_on_referenced_packages: ignore
include: package:tekartik_lints_flutter/strict.yaml

linter:
  rules:
    avoid_print: false
